src/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^reminder/$', ReminderView.as_view(), name='reminder'),
    url(r'^reminder/success/$', ReminderSuccessView.as_view(), name='reminder_success'),
    url(r'^librarian/add/$', AddLibrarian.as_view(), name='add_librarian'),
    url(r'^reader/add/$', AddReader.as_view(), name='add_reader'),
    url(r'^profile/librarian/$', ProfileLibrarianView.as_view(), name='profile_librarian'),
    url(r'^profile/reader/(?P<pk>[\d-]+)/edit/$', ProfileReaderEditView.as_view(), name='profile_reader_edit'),
    url(r'^refresh/(?P<token>.+\/)/$', RefreshPasswordView.as_view(), name='refresh_password'),
    url(r'^profile/reader/$', ProfileReaderView.as_view(), name='profile_reader'),
    url(r'^api/reader/change_request/$', ChangeProfileRequestApiView.as_view(), name='change_request'),

]

src/elcat/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^books/add/$', AddBookView.as_view(), name='add_book'),
    url(r'^search/?$', SearchResult.as_view(), name='search_result'),
    url(r'^api/readers/$', ApiReadersView.as_view(), name='api_readers'),
    url(r'^api/bookinfo/(?P<pk>[\d-]+)/$', ApiBookInfoView.as_view(), name='api_bookinfo'),
    url(r'^api/bookorder/(?P<pk>[\d-]+)/$', ApiBookOrderView.as_view(), name='api_bookorder'),
    url(r'^api/booktransfer/complete/(?P<pk>[\d-]+)/$', ApiBookOrderClose.as_view(), name='api_book_transfer_complete'),
    url(r'^api/issues/(?P<pk>[\d-]+)/$', ApiBookIssueView.as_view(), name='api_issued'),
    url(r'^api/bookback/(?P<pk>[\d-]+)/$', ApiBookBackView.as_view(), name='api_bookback'),
    url(r'^api/prolonged/(?P<pk>[\d-]+)/$', ApiBookProlongedView.as_view(), name='api_prolonged'),
    url(r'^api/cancellation/(?P<pk>[\d-]+)/$', ApiBookCancellationView.as_view(), name='api_cancellation'),

]

src/instabook/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^elcat/', include('elcat.urls', namespace='elcat')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^doc/', include('documentation.urls', namespace='docs')),
]

src/reports/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^reports/list/$', ListReports.as_view(), name='list'),
    url(r'^reports/(?P<pk>[\d-]+)/exec/$', ExecReport.as_view(), name='exec'),


]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.utils import timezone
import datetime
from elcat.models import library, book
from .managers import CustomUserManager, OrderBooksManager, UserReminderRequestManager
from .signals import book_order_close, book_order_create


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField('username', max_length=150, unique=False)
    first_name = models.CharField('Имя', max_length=150, blank=True)
    middle_name = models.CharField('Отчество', max_length=150, blank=True)
    last_name = models.CharField('Фамилия', max_length=150, blank=True)
    email = models.EmailField('email address', blank=True, unique=True)
    is_staff = models.BooleanField('staff status', default=False)
    is_active = models.BooleanField('active', default=True, )
    date_joined = models.DateTimeField('date joined', default=timezone.now)
    edit_request = models.BooleanField('edit_request', default=False)
    self_number = models.CharField('self_number', max_length=150, blank=True)
    ticket_number = models.CharField('ticket_number', max_length=150, blank=True)
    phone = models.CharField('phone', max_length=150, blank=True)
    library = models.ForeignKey(library, verbose_name='library', blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = (
            ("add_librarian", "add_librarian"),
            ("add_book", "add_book"),
            ("cancellation_book", "cancellation_book"),
            ("add_reader", "add_reader"),
        )

    def __str__(self):
        return "%s %s %s" % (self.last_name, self.first_name, self.middle_name) if self.last_name != "" else self.email

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        if self.last_name != "" and self.middle_name != "" and self.first_name != "":
            return '%s %s.%s.' % (self.last_name, self.first_name[0], self.middle_name[0])
        return self.email

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('accounts:profile_reader_edit', kwargs={'pk': self.pk})


class IssuedBooks(models.Model):
    start_date = models.DateField(default=timezone.now)
    book = models.ForeignKey(book, verbose_name='Книга')
    reader = models.ForeignKey(User, verbose_name='Читатель')
    prolong_request = models.BooleanField(verbose_name='Запрошено продление', default=False)

    class Meta:
        verbose_name = 'Выданная книга'
        verbose_name_plural = 'Выданные книги'

    def __str__(self):
        return '%s [%s]' % (self.book.name, self.reader.get_short_name())

    def prolong(self, days=7):
        date = timezone.now()
        self.start_date = date + datetime.timedelta(days=days)
        self.save()


class BookOrder(models.Model):
    date_created = models.DateTimeField(verbose_name='Дата и время создания',
                                        default=timezone.now)
    reader = models.ForeignKey(User, verbose_name='Читатель')
    book = models.ForeignKey(book, verbose_name='книга')
    closed = models.BooleanField(verbose_name='Заказ закрыт', default=False)
    objects = OrderBooksManager()

    class Meta:
        verbose_name = 'Заказ на межбиблиотечный обмен'
        verbose_name_plural = 'Заказы на межбиблиотечный обмен'

    def __str__(self):
        return '%s; %s' % (self.book.name, self.reader.get_short_name())

    def close_order(self):
        self.closed = True
        self.save()
        book_order_close.send(self, book_order=self)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        send_signal = self.pk is None
        super(BookOrder, self).save(force_insert, force_update, using, update_fields)
        if send_signal:
            book_order_create.send(self, book_order=self)


class UserReminderRequest(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь')
    token = models.CharField(verbose_name='Токен', max_length=150)
    created = models.DateTimeField(default=timezone.now)

    objects = UserReminderRequestManager()

    class Meta:
        verbose_name = 'Заброс на сброс пароля'
        verbose_name_plural = 'Запросы на срос пароля'

    def __str__(self):
        return '%s:%s' % (self.user.get_short_name(), self.created)

    def get_absolute_url(self):
        return reverse_lazy('accounts:refresh_password', kwargs={'token': self.token})

src/accounts/forms.py
from django import forms
from .models import User


class AuthForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)


class EditLibrarianForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, required=True)
    confirm_password = forms.CharField(widget=forms.PasswordInput, required=True)

    class Meta:
        model = User
        fields = [
            'first_name',
            'middle_name',
            'last_name',
            'self_number',
            'ticket_number',
            'library',
            'phone',
            'email']
class EditProfileLibrarianForm(forms.ModelForm):


    class Meta:
        model = User
        fields = [
            'first_name',
            'middle_name',
            'last_name',
            'self_number',
            'ticket_number',
            'library',
            'phone',
            'email']


class AddReaderForm(EditLibrarianForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'middle_name',
            'last_name',
            'ticket_number',
            'phone',
            'email']


class EditReaderForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, required=False)

    class Meta:
        model = User
        fields = [
            'first_name',
            'middle_name',
            'last_name',
            'ticket_number',
            'phone',
            'email']

src/accounts/views.py
from django.views.generic import FormView, TemplateView, UpdateView, View, DetailView
from django.utils import timezone
from django.shortcuts import redirect, HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from elcat.models import library
import json
from .forms import AuthForm, EditLibrarianForm, AddReaderForm, EditReaderForm, EditProfileLibrarianForm
from .models import User, UserReminderRequest


class LoginView(FormView):
    template_name = 'accounts_login.html'
    form_class = AuthForm
    formError = ''

    def form_valid(self, form):
        data = form.cleaned_data
        user = authenticate(email=data['email'], password=data['password'])
        if user is not None:
            login(self.request, user)
            return redirect('/')
        self.formError = 'Email или пароль не распознаны.'
        return self.form_invalid(form)

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        context['formError'] = self.formError
        return self.render_to_response(context)


class AddLibrarian(PermissionRequiredMixin, FormView):
    template_name = 'accounts_add_librarian.html'
    form_class = EditLibrarianForm
    permission_required = 'accounts.add_librarian'

    form_error = ""

    def form_valid(self, form):
        success = True
        data = form.cleaned_data
        if data['password'] != data['confirm_password']:
            success = False
            self.form_error += 'Пароли не совпадают\n'
        if success:
            user = User.objects.register_librarian(data)
            if not user:
                success = False
                self.form_error += 'Email занят\n'
        if not success:
            return self.form_invalid(form)

        return super(AddLibrarian, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(AddLibrarian, self).get_context_data()
        context['form_error'] = self.form_error
        context['library_list'] = library.objects.all()
        return context

    def get_success_url(self):
        return reverse_lazy('accounts:add_librarian')


class AddReader(AddLibrarian):
    template_name = 'accounts_add_reader.html'
    form_class = AddReaderForm
    permission_required = 'accounts.add_reader'

    def form_valid(self, form):
        success = True
        data = form.cleaned_data
        if data['password'] != data['confirm_password']:
            success = False
            self.form_error += 'Пароли не совпадают\n'
        if success:
            data['library'] = self.request.user.library
            user = User.objects.register_reader(data)
            if not user:
                success = False
                self.form_error += 'Email занят\n'
        if not success:
            return self.form_invalid(form)

        return super(AddLibrarian, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('accounts:add_reader')


class ProfileLibrarianView(PermissionRequiredMixin, UpdateView):
    permission_required = 'accounts.add_reader'
    template_name = 'accounts_profile_librarian.html'
    form_class = EditProfileLibrarianForm

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super(ProfileLibrarianView, self).get_context_data()
        context["library_list"] = library.objects.all()
        return context


class ProfileReaderView(TemplateView):
    template_name = 'accounts_profile_reader.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileReaderView, self).get_context_data()
        context['reader'] = self.request.user
        return context

    def post(self, request, *argw, **kwargs):
        request.user.edit_request = True
        request.user.save()
        return super(ProfileReaderView, self).post(request, *argw, **kwargs)


class ProfileReaderEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'accounts_profile_reader.html'
    permission_required = 'accounts.add_reader'
    model = User
    pk_url_kwarg = 'pk'
    context_object_name = 'reader'
    form_class = EditReaderForm

    def post(self, request, *args, **kwargs):
        reader = self.get_object()
        if not reader.edit_request:
            return redirect(reader.get_absolute_url())
        return super(ProfileReaderEditView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        data = form.cleaned_data
        passwd = data['password']
        if passwd:
            reader = self.get_object()
            reader.set_password(passwd)
            reader.save()
        return super(ProfileReaderEditView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        return super(ProfileReaderEditView, self).get_context_data()


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('/')


class ChangeProfileRequestApiView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        request.user.edit_request = True
        request.user.save()

        return HttpResponse(json.dumps({"success": True}), content_type='application/json')


class RefreshPasswordView(DetailView):
    template_name = 'accounts_refresh_password.html'
    model = UserReminderRequest
    slug_field = 'token'
    slug_url_kwarg = 'token'

    def dispatch(self, request, *args, **kwargs):
        if not self.is_valid_token():
            context = self.get_context_data()
            context['token_is_expire'] = True
            return self.render_to_response(context)
        return super(RefreshPasswordView, self).dispatch(request, args, kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        password = request.POST.get('password', None)
        password_confirm = request.POST.get('password_confirm', None)
        context = self.get_context_data()
        if not password or not password_confirm or password == '' or password_confirm == '':
            context['error'] = 'Заполните все поля'
            return self.render_to_response(context)
        if password != password_confirm:
            context['error'] = 'Пароли не совпадают'
            return self.render_to_response(context)
        req = self.get_object()
        req.user.set_password(password)
        req.user.save()
        req.delete()

        return redirect(reverse_lazy('accounts:login'))

    def is_valid_token(self):
        req = self.get_object()
        nowDate = timezone.now()
        delta = nowDate - req.created
        return delta.days <= 4


class ReminderSuccessView(TemplateView):
    template_name = 'accounts_reminder_success.html'


class ReminderView(TemplateView):
    template_name = 'accounts_reminder.html'

    MESSAGE_TEMPLATE = '''Вас приветсвует АБИС Белоярской ЦБС
Для восстановления забытого пароля посетите эту ссылку => http://is.bellib.ru%s
Если Вы не запрашивали смену пароля, то проигнорируйте это письмо.'''

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email', None)
        context = self.get_context_data()
        if not email:
            context['error'] = 'Введите свой email'
            return self.render_to_response(context)
        try:
            user = User.objects.get(email=email)
            reminder = UserReminderRequest.objects.generate_new(user)
            user.email_user('Восстановление пароля', self.MESSAGE_TEMPLATE % reminder.get_absolute_url())
        except Exception as e:
            context['error'] = 'E-mail не найден'
            return self.render_to_response(context)
        return redirect(reverse_lazy('accounts:reminder_success'))

src/accounts/templates/accounts_add_librarian.html
{% extends 'base.html' %}
{% block content %}
    <section class="breadcrumb__section breadcrumb__container_margin-top">
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="/">Главная</a></li>
                <li class="active">Регистрация библиотекаря</li>
            </ol>
        </div>
    </section>

    <section class="search__section common__container_margin-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12 common__container_margin-bottom">
                    <h2 class="text-center">
                        Регистрация библиотекаря
                    </h2>

                    <form id="validateThisID" data-js-validation="true" novalidate class="" action="." method="post">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="inputLastName">
                                Фамилия *
                            </label>
                            <input type="text" class="form-control" id="inputLastName" placeholder="Фамилия"
                                   name="last_name"
                                   value="{{ form.last_name.value|default:'' }}"
                                   data-validation-require="true"
                                    >
                            <span class="help-block"></span>
                        </div>
                        <div class="form-group">
                            <label for="inputFirstName">
                                Имя *
                            </label>
                            <input type="text" class="form-control" id="inputFirstName" placeholder="Имя"
                                   data-validation-require="true"
                                   value="{{ form.first_name.value|default:'' }}"
                                   name="first_name"
                                    >
                            <span class="help-block"></span>
                        </div>
                        <div class="form-group">
                            <label for="inputSurName">
                                Отчество *
                            </label>
                            <input type="text" class="form-control" id="inputSurName" placeholder="Отчество"
                                   name="middle_name"
                                   value="{{ form.middle_name.value|default:'' }}"
                                   data-validation-require="true"
                                    >
                            <span class="help-block"></span>
                        </div>
                        <div class="form-group">
                            <label for="inputID">
                                Номер читательского билета *
                            </label>
                            <input type="text" class="form-control" id="inputID"
                                   placeholder="Номер читательского билета"
                                   data-validation-require="true"
                                   value="{{ form.ticket_number.value|default:'' }}"
                                   name="ticket_number"
                                    >
                            <span class="help-block"></span>
                        </div>
                        <div class="form-group">
                            <label for="inputID">
                                Табельный номер сотрудника *
                            </label>
                            <input type="text" class="form-control" id="inputID"
                                   placeholder="Номер читательского билета"
                                   data-validation-require="true"
                                   value="{{ form.self_number.value|default:'' }}"
                                   name="self_number"
                                    >
                            <span class="help-block"></span>
                        </div>
                        <div class="form-group">
                            <label for="inputPhone">
                                Телефон *
                            </label>
                            <input type="tel" class="form-control" id="inputPhone" placeholder="Phone"
                                   data-validation-require="true"
                                   data-validation-templ="phone"
                                   value="{{ form.phone.value|default:'' }}"
                                   name="phone"
                                    >
                            <span class="help-block"></span>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail1">
                                Email адрес
                            </label>
                            <input type="email" class="form-control" id="inputEmail1" placeholder="Email"
                                   data-validation-require="true"
                                   data-validation-templ="email"
                                   value="{{ form.email.value|default:'' }}"
                                   name="email"
                                    >
                            <span class="help-block"></span>
                        </div>
                        <div class="form-group">
                            <label for="library_select">
                                Библиотека
                            </label>
                            <select class="form-control" name="library" id="library_select">
                                {% for library in library_list %}
                                    <option value="{{ library.library_id }}">{{ library.name }}</option>
                                {% endfor %}
                            </select>

                        </div>

                        <div class="form-group">
                            <label for="inputPassword1">
                                Пароль *
                            </label>
                            <input type="password" class="form-control" id="inputPassword1"
                                   placeholder="Пароль"
                                   data-validation-require="true"
                                   name="password">
                            <span class="help-block"></span>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword2">
                                Подтверждение пароля *
                            </label>
                            <input type="password" class="form-control" id="inputPassword2"
                                   placeholder="Пароль"
                                   data-validation-require="true"
                                   name="confirm_password">
                            <span class="help-block"></span>
                        </div>
                        {% if form_error %}
                            <span class="text-danger">{{ form_error }}</span>
                        {% endif %}
                        <button type="submit" class="btn btn-default center-block">Регистрация</button>
                    </form>

                </div>

            </div>
        </div>
    </section>

    <section class="documentation_link__section">
        <div class="container">
            <ul class="documentation_link__list">
                <li class="documentation_link__list_item">
                    <div class="alert alert-info" role="alert">
                        <span>
                            <strong>Помощь</strong> по регистрации и использованию системы доступна по ссылке:
                        </span>
                        <a href="{% url 'docs:list' %}">Инструкция по регистрации и использованию системой</a>
                    </div>
                </li>
            </ul>
        </div>
    </section>
{% endblock %}

src/accounts/templates/accounts_login.html
{% extends 'base.html' %}

{% block content %}

    <section class="breadcrumb__section breadcrumb__container_margin-top">
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="/">Главная</a></li>
                <li class="active">Вход</li>
            </ol>
        </div>
    </section>

    <section class="search__section common__container_margin-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12 common__container_margin-bottom">
                    <h2 class="text-center">
                        Вход
                    </h2>

                    <form method="post" action=".">
                        {% csrf_token %}
                        <div class="form-group {% if  form.email.errors %} has-error {% endif %}">
                            <label class="control-label" for="inputEmail">Email адрес</label>
                            <input type="email" class="form-control" name="email" required id="inputEmail" placeholder="Email"
                                   value="{{ form.email.value|default:'' }}">
                                {% for error in form.email.errors %}
                                    <span class="help-block">{{ error }}</span>
                                {% endfor %}
                        </div>
                        <div class="form-group {% if form.password.errors %} has-error {% endif %}">
                            <label for="inputPassword">Пароль</label>
                            <input type="password" class="form-control" required name="password" id="inputPassword"
                                   placeholder="Пароль">

                            {% for error in form.password.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}

                        </div>
                        {% if formError %}
                            <div class="form-group  has-error ">
                                <span class="help-block">{{ formError }}</span>
                            </div>
                        {% endif %}
                        <button type="submit" class="btn btn-default center-block">Вход</button>
                    </form>
                </div>

                <div class="col-md-12">
                    <p>
                        Если вы забыли логин или пароль, воспользуйтесь формой <a href="{% url 'accounts:reminder' %}">восстановления
                        учетных
                        данных</a>
                    </p>



                </div>
            </div>
        </div>
    </section>

    <section class="documentation_link__section">
        <div class="container">
            <ul class="documentation_link__list">
                <li class="documentation_link__list_item">
                    <div class="alert alert-info" role="alert">
                        <span>
                            <strong>Помощь</strong> по регистрации и использованию системы доступна по ссылке:
                        </span>
                        <a href="{% url 'docs:list' %}">Инструкция по регистрации и использованию системой</a>
                    </div>
                </li>
            </ul>
        </div>
    </section>


{% endblock %}

src/accounts/templates/accounts_refresh_password.html
{% extends 'base.html' %}

{% block content %}

    <section class="breadcrumb__section breadcrumb__container_margin-top">
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="/">Главная</a></li>
                <li class="active">Восстановление учетных данных</li>
            </ol>
        </div>
    </section>

    <section class="search__section common__container_margin-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12 common__container_margin-bottom">
                    <h2 class="text-center">
                        Восстановление учетных данных
                    </h2>
                    {% if token_is_expire %}
                        <h3>Ссылка устарела.</h3>
                        <p>Попробуйте запросить <a href="{% url 'accounts:reminder' %}">новую</a></p>
                    {% else %}
                        <form action="." method="post">
                            {% csrf_token %}

                            <div class="form-grou {% if error %} has-warning {% endif %}">
                                <label for="inputEmail">
                                    Пароль
                                </label>
                                <input type="password" name="password" class="form-control" id="inputPassword" required
                                       placeholder="Пароль">
                                {% if error %}
                                    <span class="help-block">{{ error }}</span>
                                {% endif %}
                            </div>
                            <div class="form-grou {% if error %} has-warning {% endif %}">
                                <label for="inputPasswordConfirm">
                                    Подтверждение
                                </label>
                                <input type="password" name="password_confirm" class="form-control"
                                       id="inputPasswordConfirm" required
                                       placeholder="Подтверждение">
                                {% if error %}
                                    <span class="help-block">{{ error }}</span>
                                {% endif %}
                            </div>

                            <button type="submit" class="btn btn-default center-block">Сохранить</button>
                        </form>
                    {% endif %}

                </div>

            </div>
        </div>
    </section>




{% endblock %}