src/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^reminder/$', ReminderView.as_view(), name='reminder'),
    url(r'^reminder/success/$', ReminderSuccessView.as_view(), name='reminder_success'),
    url(r'^librarian/add/$', AddLibrarian.as_view(), name='add_librarian'),
    url(r'^reader/add/$', AddReader.as_view(), name='add_reader'),
    url(r'^profile/librarian/$', ProfileLibrarianView.as_view(), name='profile_librarian'),
    url(r'^profile/reader/(?P<pk>[\d-]+)/edit/$', ProfileReaderEditView.as_view(), name='profile_reader_edit'),
    url(r'^refresh/(?P<token>.+\/)/$', RefreshPasswordView.as_view(), name='refresh_password'),
    url(r'^profile/reader/$', ProfileReaderView.as_view(), name='profile_reader'),
    url(r'^api/reader/change_request/$', ChangeProfileRequestApiView.as_view(), name='change_request'),

]

src/elcat/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^books/add/$', AddBookView.as_view(), name='add_book'),
    url(r'^search/?$', SearchResult.as_view(), name='search_result'),
    url(r'^api/readers/$', ApiReadersView.as_view(), name='api_readers'),
    url(r'^api/bookinfo/(?P<pk>[\d-]+)/$', ApiBookInfoView.as_view(), name='api_bookinfo'),
    url(r'^api/bookorder/(?P<pk>[\d-]+)/$', ApiBookOrderView.as_view(), name='api_bookorder'),
    url(r'^api/booktransfer/complete/(?P<pk>[\d-]+)/$', ApiBookOrderClose.as_view(), name='api_book_transfer_complete'),
    url(r'^api/issues/(?P<pk>[\d-]+)/$', ApiBookIssueView.as_view(), name='api_issued'),
    url(r'^api/bookback/(?P<pk>[\d-]+)/$', ApiBookBackView.as_view(), name='api_bookback'),
    url(r'^api/prolonged/(?P<pk>[\d-]+)/$', ApiBookProlongedView.as_view(), name='api_prolonged'),
    url(r'^api/cancellation/(?P<pk>[\d-]+)/$', ApiBookCancellationView.as_view(), name='api_cancellation'),

]

src/instabook/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^elcat/', include('elcat.urls', namespace='elcat')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^doc/', include('documentation.urls', namespace='docs')),
]

src/reports/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^reports/list/$', ListReports.as_view(), name='list'),
    url(r'^reports/(?P<pk>[\d-]+)/exec/$', ExecReport.as_view(), name='exec'),


]

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>


<section class="navbar__section">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">БЦБС</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">Меню системы <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "elcat:search_result" %}">Поиск</a></li>
                            {% if user.is_authenticated %}
                                <li role="separator" class="divider"></li>
                                {% if perms.accounts.add_book %}
                                    <li><a href="{% url "elcat:add_book" %}">Пополнение БД книг</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li ><a href="{% url 'reports:list' %}">Аналитическая работа с БД</a></li>
                                    <li role="separator" class="divider"></li>
                                {% endif %}
                                {% if perms.accounts.add_reader %}
                                    <li><a href="{% url "accounts:add_reader" %}">Регистрация читателя</a></li>
                                {% endif %}
                                {% if perms.accounts.add_librarian %}
                                    <li><a href="{% url "accounts:add_librarian" %}">Регистрация библиотекаря</a></li>
                                {% endif %}

                            {% endif %}
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url "docs:list" %}">Документация</a></li>
                        </ul>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_anonymous %}
                        {% if perms.accounts.add_book %}
                            <li><a href="{% url "accounts:profile_librarian" %}">{{ user.username }}</a></li>
                        {% else %}
                            <li><a href="{% url "accounts:profile_reader" %}">{{ user.username }}</a></li>

                        {% endif %}
                        <li><a href="{% url "accounts:logout" %}">Выход</a></li>
                    {% else %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">Вход<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                {% if user.is_anonymous %}
                                    <li><a href="{% url 'accounts:login' %}">Вход в систему</a></li>

                                {% endif %}

                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</section>


{% block content %}{% endblock %}

<section class="footer">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
            <div>
                <p class="text-center">
                    <i class="fa fa-copyright" aria-hidden="true"></i>2017 Иванов Дмитрий Сергеевич
                </p>
            </div>
        </div>
    </div>
</section>

<script
        src="http://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="{% static 'dist/app.bundle.js' %}"></script>

{% block js_extra %}

{% endblock %}
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

    <section class="breadcrumb__section breadcrumb__container_margin-top">
        <div class="container">
            <ol class="breadcrumb">
                <li class="active">Главная</li>

            </ol>
        </div>
    </section>

    <section class="jumbotron__section">
        <div class="container">
            <div class=""></div>
            <div class="jumbotron">

                <h2 class="text-center">
                    ЭБС Белоярской ЦБС ХМАО-Югра
                </h2>

                <img src="{% static 'img/bl__mainpage.jpg' %}" class="img-responsive center-block" alt="Библиотека">

            </div>
        </div>
    </section>

    <section class="search__section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="text-center">
                        Поиск книг
                    </h2>

                    <form action="/elcat/search/" method="get">
                        <div class="form-group">
                            <label class="control-label sr-only" for="searchRequestMainPage">Поиск</label>
                            <input type="text" class="form-control" id="searchRequestMainPage" name="q"
                                   aria-describedby="searchHelpBlock" placeholder="Введите запрос...">
                            <span id="searchHelpBlock" class="help-block"></span>
                        </div>

                        <div class="form-group">
                            <div class="">
                                <button type="submit" class="btn btn-default center-block">Поиск</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}